config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'
  
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

  get '/provinces', to: 'provinces#get_by_country', as: 'provinces'

  get '/company', to: 'companies#dashboard', as: 'company_dashboard'

  get '/student', to: 'students#dashboard', as: 'student_dashboard'
  post '/student/update_profile', to: 'students#update_profile', as: 'update_student_profile'
  post '/student/experience', to: 'students#create_experience', as:'create_student_experience'
  delete '/student/:id/experience', to: 'students#destroy_experience', as: 'destroy_student_experience'
  get '/student/company', to: 'students#company_profile', as: 'student_company_profile'
  post '/student/skill', to: 'students#create_skill', as:'create_student_skill'
  post '/student/verify', to: 'students#verify_skills', as: 'verify_student_skills'
  delete '/student/:id/skill', to: 'students#destroy_skill', as: 'destroy_student_skill'
  get '/student/interview/:id/accept', to: 'students#accept_interview', as: 'accept_interview'
  get '/student/interview/:id/deny', to: 'students#deny_interview', as: 'deny_interview'
  delete '/student/:id/interview', to: 'students#destroy_interview', as: 'destroy_student_interview'

  get '/company/profile', to: 'companies#profile', as: 'company_profile'
  post '/company/profile', to: 'companies#update_profile', as: 'company_profile_update'
  post '/company/position', to: 'companies#position', as: 'company_position'
  delete '/company/:id/position', to: 'companies#destroy_position', as: 'company_position_destroy'
  get '/company/candidate', to: 'candidates#new', as: 'company_candidate'
  get '/company/candidate/student', to: 'candidates#get_student', as: 'candidate_profile'
  post '/company/candidate/request-interview', to: 'candidates#request_interview', as: 'request_interview'

  get '/company/interview', to: 'interviews#interview_sent', as: 'interview_sent'
  get '/company/interview-scheduled', to: 'interviews#interview_scheduled', as: 'interview_scheduled'
  get '/company/interview-denied', to: 'interviews#interview_denied', as: 'interview_denied'
  delete '/company/:id/interview', to: 'interviews#destroy', as: 'destroy_interview'
  get '/company/:id/interview', to: 'interviews#view', as: 'view_interview'

end

app/controllers/student_controller.rb
class StudentsController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_basedata

  def dashboard
    @student = current_user
    @interviews = @student.student_interviews.sent
    @interviews_scheduled = @student.student_interviews.scheduled

    @experience = Experience.new
    @experiences = @student.experiences

    @skill = Skill.new
    @skills = @student.skills
  end

  def update_profile

    @student = current_user
    if @student.update_attributes permit_params
      redirect_to student_dashboard_path, :notice => "Profile is successfully updated."
    else
      redirect_to student_dashboard_path, :alert => "Failed to update profile."
    end

  end

  def create_experience
    @experience = current_user.experiences.build permit_experience_params

    if @experience.save
      redirect_to student_dashboard_path, :notice => "Experience is successfully saved."
    else
      redirect_to student_dashboard_path, :alert => "Failed to save experience."
    end
  end

  def destroy_experience
    @exp = current_user.experiences.find params[:id]

    if @exp.destroy
      redirect_to student_dashboard_path, notice: "Experience was successfully deleted."
    else
      redirect_to student_dashboard_path, alert: "Failed to delete experience."
    end
  end

  def create_skill
    @skill = current_user.skills.build permit_skill_params

    if @skill.save
      redirect_to student_dashboard_path, :notice => "Skill is successfully saved."
    else
      redirect_to student_dashboard_path, :alert => "Failed to save skill."
    end
  end

  def destroy_skill
    @sk = current_user.skills.find params[:id]

    if @sk.destroy
      redirect_to student_dashboard_path, notice: "Skill was successfully deleted."
    else
      redirect_to student_dashboard_path, alert: "Failed to delete skill."
    end
  end
  
  def verify_skills
    current_user.skills.each do |skill|
      skill_list = SkillList.find_by_name(skill.skill)
      student_test = StudentTest.find_or_create_by(
        :user_id       => current_user.id,
        :skill_list_id => skill_list.id
      )

      if student_test.result.nil? || student_test.result < 80.0
        student_test.result = 100.00
        student_test.save
      end
    end
    
    if true
      redirect_to student_dashboard_path, notice: "Skills successfully verified."
    else
      redirect_to student_dashboard_path, alert: "Failed to verify skills."
    end
  end

  def company_profile
    company = User.find(params[:id])
    interview = Interview.find(params[:interview_id])

    if company.nil?
      render :json => {errors: "Could not retrieve company profile."}, status: :unprocessible_entity and return
    else
      company_json = {
        :company_id     => company.id,
        :company_name   => company.company_name,
        :name           => company.name,
        :email          => company.email,
        :country        => company.country_id.nil? ? '' : Country.find(company.country_id).name,
        :position       => company.position,
        :phone_number   => company.phone_number,
        :website        => company.website,
        :photo          => company.photo.url,
        :interview_id   => interview.id,
        :interview_date => interview.interview_datetime.strftime("%Y-%m-%d %I:%M %p"),
        :interview_desc => interview.description
      }.to_json

      render :json => {
        :success => true, 
        :company => company_json
      }, status: :created and return
    end
  end

  def accept_interview
    interview = Interview.find(params[:id])
    interview.update_attributes :status => Interview::ACCEPTED

    redirect_to student_dashboard_path
  end

  def deny_interview
    interview = Interview.find(params[:id])
    interview.update_attributes :status => Interview::DENIED

    redirect_to student_dashboard_path
  end

  def destroy_interview
    interview = Interview.find(params[:id])
    interview.destroy

    redirect_to student_dashboard_path
  end

  private

  def permit_params
    if params[:user][:password].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end

    if params[:user][:photo].blank?
      params[:user].delete :photo
    end

    params.require(:user).permit :email, :password, :name, :phone_number, :birth_year, :photo,
                                 :academic_status, :study_field_id, :school, :major
  end

  def permit_experience_params
    params.require(:experience).permit :experience, :date_from, :date_to
  end

  def permit_skill_params
    params.require(:skill).permit :skill
  end
end

app/views/students/_matched_company.slim
.modal.fade.in#matched_company
  .modal-dialog
    .modal-content
      .modal-header.text-center
        button.close data-dismiss="modal" x
        h3.semibold.modal-title.text-success Company Profile
      .modal-body.bgcolor-white
        .row
          .col-md-6.text-center
            img#profile_photo width="100%"
          .col-md-6
            address
              strong Name: 
              span#profile_name Dennis Chan
            address
              strong Company Name: 
              span#profile_companyname Google
            address
              strong Email: 
              span#profile_email dennischan8782@gmail.com
            address
              strong Phone Number: 
              span#profile_phonenumber 111-111-1111
            address
              strong Company Website: 
              span#profile_website www
            address
              strong Country: 
              span#profile_country China
            address
              strong Position: 
              span#profile_position CTO
        hr
        .row
          .col-md-12.text-center
            h3.semibold.modal-title.text-success.pb10 Interview Request
            .row
              .col-md-6.text-right
                strong Interview Date:
              .col-md-6.text-left
                #interview_date Dennis Chan
            .row
              .col-md-6.text-right.mt5
                strong Interview Description:
              .col-md-6.text-left.mt5
                #interview_description Google
      .modal-footer
        .row
          .col-md-4.col-md-offset-4
            = link_to 'Accept', '#', class: "btn btn-success", id: "accept_btn"
            = link_to 'Deny', '#', class: "btn btn-success", id: "deny_btn"

app/views/students/dashboard.slim
/! START Template Header
header#header.navbar.navbar-fixed-top
  /! START navbar header
  .navbar-header
    /! Brand
    a.navbar-brand href="javascript:void(0);" 
      span.logo-figure.dream-logo-figure
    /! / Brand
  /! START Toolbar
  .navbar-toolbar.clearfix
    /! START Right nav
    ul.nav.navbar-nav.navbar-right
      /! Profile dropdown
      li.dropdown.profile
        = link_to destroy_user_session_path, class: "dropdown-toggle", method: :delete
          span.meta
            span.avatar
              = image_tag @student.photo.url(:thumb), class: 'img-circle'
            span.text.hidden-xs.hidden-sm.pl5 Sign Out
/! / END Template Header

/! START Template Main
section#main role="main" 
  /! START Template Container
  .container

    /! START row
    .row
      /! Left / Top Side
      .col-sm-3
        /! figure with progress
        ul.list-table
          li.text-center
            = image_tag @student.photo.url, class: '', width: "100%"
        br
        br
        /! tab menu
        h5.text-primary.semibold.mt0 
          span.ico-newspaper
          | &nbsp;Matched Positions
        - if @interviews.count == 0
          span No available positions
        - else
          - @interviews.each do |i|
            h5
              a href="#" remote="true" data-toggle="modal" onclick="showCompanyProfile(#{i.company_id}, #{i.id})" 
                = i.position.name
              span.pull-right #{i.matching_score}%
            .progress.progress-xs.mtb5
              .progress-bar.progress-bar-warning style=("width: #{i.matching_score}%") 
            br
       
      /! / Left / Top Side
      /! Left / Bottom Side
      .col-sm-9
        = render 'shared/messages'
        /! START Tab-content
        .tab-content
          /! START panel
          .panel.panel-default.form-horizontal.form-bordered
            /! panel heading/header
            .panel-heading.pt0.pb0
              h4.semibold.text-primary 
                small.text-primary
                  i.ico-list
                | &nbsp;Scheduled Interviews
            /! / panel heading/header
            /! panel body
            .panel-body
              .table-responsive.panel-collapse.pull.out
                - if @interviews_scheduled.length != 0
                  table.table.table-bordered.table-hover
                    thead
                      tr
                        th Position
                        th Company
                        th Email
                        th Sent Date
                        th Interview Date
                        th Action
                    tbody
                    - @interviews_scheduled.each do |i|
                      tr
                        td.td-vmiddle = i.try(:position).try(:name)
                        td.td-vmiddle
                          .media-object
                            = image_tag i.company.photo.url(:thumb), class: 'img-circle'
                          span &nbsp;&nbsp; #{i.company.name}
                        td.td-vmiddle = i.company.email
                        td.td-vmiddle = i.sent_date.strftime("%Y-%m-%d %H:%M:%S")
                        td.td-vmiddle = i.interview_datetime.strftime("%Y-%m-%d %H:%M:%S")
                        td.text-center.td-vmiddle
                          = link_to destroy_student_interview_path(i), class: 'btn btn-danger btn-xs', title: 'Delete',method: :delete, 'data-confirm' => 'Are you sure?' do
                            span.ico-remove3
                - else
                  h6.semibold.text-center No records

          /! tab-pane: profile
          #profile.tab-pane.active
            /! form profile
            = form_for @student, url: update_student_profile_path, method: :post, html: { multipart: true, class: 'panel panel-default' } do |f|
              /!= render partial: 'shared/form_errors', locals: {model: f.object}
              .panel-heading.pt0.pb0
                h4.semibold.text-primary 
                  small.text-primary
                    i.ico-list
                  | &nbsp;Personal Information
              .panel-body
                .form-group
                  .row
                    .col-sm-6
                      = f.label :name, 'Name', class: 'control-label'
                      = f.text_field :name, class: "form-control", placeholder: "Your name"
                    .col-sm-6
                      = f.label :email, 'Email', class: 'control-label'
                      = f.email_field :email, class: "form-control", placeholder: "you@example.com", type: "email"
                .form-group
                  .row
                    .col-sm-6
                      = f.label :password, 'Password', class: 'control-label'
                      = f.text_field :password, class: 'form-control', type: "password"
                    .col-sm-6
                      = f.label :password_confirmation, 'Password Confirmation', class: 'control-label'
                      = f.text_field :password_confirmation, class: 'form-control', type: "password"
                .form-group
                  .row
                    .col-sm-6
                      = f.label :phone_number, 'Phone Number', class: 'control-label'
                      = f.telephone_field :phone_number, class: "form-control", placeholder: "+1-555-555-5555"
                    .col-sm-6
                      = f.label :school, 'School', class: 'control-label'
                      = f.text_field :school, class: "form-control", placeholder: "School"
                .form-group
                  .row
                    .col-sm-6
                      = f.label :birth_year, 'Year of Birth', class: 'control-label'
                      = f.number_field :birth_year, class: 'form-control', placeholder: "1991"
                    .col-sm-6
                      = f.label :academic_status, 'Current Academic Status', class: 'control-label'
                      = f.text_field :academic_status, class: 'form-control', placeholder: "High School"
                .form-group
                  .row
                    .col-sm-6
                      = f.label :study_field_id, 'Field of Study', class: 'control-label'
                      = f.select :study_field_id, @study_fields.collect {|c| [c.name, c.id]}, {}, class: 'form-control', placeholder: "Select..."
                    .col-sm-6
                      = f.label :major, 'Major', class: 'control-label'
                      = f.text_field :major, class: "form-control", placeholder: "Major"
                .form-group
                  .row
                    .col-md-6
                      = f.label :photo, 'Photo', class: 'control-label'
                      = f.file_field :photo, class: 'form-control'
              .panel-footer.text-right
                = f.button 'Save Changes', class: 'btn btn-success'

          /! tab-pane: Experiences
          #profile.tab-pane.active
            /! form profile
            .form.panel.panel-default
              .panel-heading.pt0.pb0
                h4.semibold.text-primary 
                  small.text-primary
                    i.ico-list
                  | &nbsp;Experiences
              .panel-body
                br
                .table-responsive.panel-collapse.pull.out
                  table#table1.table.table-bordered.table-hover
                    thead
                      tr
                        th width="50%" Experience
                        th width="30%" Date
                        th width="20%" Action
                    tbody
                      - @experiences.each do |exp|
                        tr
                          td.td-vmiddle = exp.experience
                          td.td-vmiddle = exp.date_from.to_s + " ~ " + exp.date_to.to_s
                          td.text-center
                            = link_to destroy_student_experience_path(exp), class: 'btn btn-danger btn-xs', method: :delete, 'data-confirm' => 'Are you sure?' do
                              span.ico-remove3
                br
                = form_for @experience, url: create_student_experience_path, method: :post do |e|
                  .form-group
                    .row
                      .col-sm-4
                        = e.label :experience, 'Experience', class: 'control-label'
                        = e.text_field :experience, class: "form-control", placeholder: "Type experience here"
                      .col-sm-4
                        = e.label :date_from, 'From', class: 'control-label'
                        /!= e.date_select :date_from, {start_year: 1980}, class: 'form-control'
                        = e.text_field :date_from,  class: 'form-control', placeholder: "YYYY-MM-DD"
                      .col-sm-4
                        = e.label :date_to, 'To', class: 'control-label'
                        = e.text_field :date_to,  class: 'form-control', placeholder: "YYYY-MM-DD"
                  .panel-footer.text-right
                    = e.button 'Add', class: 'btn btn-success'

          /! tab-pane: Skills
          #profile.tab-pane.active
            /! form profile
            .form.panel.panel-default
              .panel-heading.pt0.pb0
                h4.semibold.text-primary 
                  small.text-primary
                    i.ico-list
                  | &nbsp;Skills
              .panel-body.text-center
                br
                = form_for @skill, url: create_student_skill_path, method: :post do |s|
                  .row
                    .col-sm-8.col-sm-offset-2
                      .col-sm-6
                        = s.select :skill, @skill_lists.collect {|c| [c.name, c.name]}, {prompt: 'Select skill'}, class: 'form-control', placeholder: "Type skill here"
                      .col-sm-6.no-padding
                        .col-sm-6.pl5
                          = s.submit 'Add', class: "btn btn-success btn-block"
                br
                .row
                  - @skills.each do |sk|
                    .col-lg-2.col-md-3.col-sm-4.col-xs-6.mb10
                      .alert.alert-info.skill-note
                        = link_to destroy_student_skill_path(sk), class: "btn close", method: :delete
                          | x
                        strong
                          =sk.skill
                br
                = form_for @skill, url: verify_student_skills_path, method: :post do |s|
                  .row
                    .col-sm-8.col-sm-offset-2
                      .col-sm-6.no-padding
                        .col-sm-6.pl5.pr5
                          = s.submit 'Verify', class: "btn btn-success btn-block"
== render 'students/matched_company'              