config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'
  
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

  get '/provinces', to: 'provinces#get_by_country', as: 'provinces'

  get '/company', to: 'companies#dashboard', as: 'company_dashboard'

  get '/student', to: 'students#dashboard', as: 'student_dashboard'
  post '/student/update_profile', to: 'students#update_profile', as: 'update_student_profile'
  post '/student/experience', to: 'students#create_experience', as:'create_student_experience'
  delete '/student/:id/experience', to: 'students#destroy_experience', as: 'destroy_student_experience'
  get '/student/company', to: 'students#company_profile', as: 'student_company_profile'
  post '/student/skill', to: 'students#create_skill', as:'create_student_skill'
  post '/student/verify', to: 'students#verify_skills', as: 'verify_student_skills'
  delete '/student/:id/skill', to: 'students#destroy_skill', as: 'destroy_student_skill'
  get '/student/interview/:id/accept', to: 'students#accept_interview', as: 'accept_interview'
  get '/student/interview/:id/deny', to: 'students#deny_interview', as: 'deny_interview'
  delete '/student/:id/interview', to: 'students#destroy_interview', as: 'destroy_student_interview'

  get '/company/profile', to: 'companies#profile', as: 'company_profile'
  post '/company/profile', to: 'companies#update_profile', as: 'company_profile_update'
  post '/company/position', to: 'companies#position', as: 'company_position'
  delete '/company/:id/position', to: 'companies#destroy_position', as: 'company_position_destroy'
  get '/company/candidate', to: 'candidates#new', as: 'company_candidate'
  get '/company/candidate/student', to: 'candidates#get_student', as: 'candidate_profile'
  post '/company/candidate/request-interview', to: 'candidates#request_interview', as: 'request_interview'

  get '/company/interview', to: 'interviews#interview_sent', as: 'interview_sent'
  get '/company/interview-scheduled', to: 'interviews#interview_scheduled', as: 'interview_scheduled'
  get '/company/interview-denied', to: 'interviews#interview_denied', as: 'interview_denied'
  delete '/company/:id/interview', to: 'interviews#destroy', as: 'destroy_interview'
  get '/company/:id/interview', to: 'interviews#view', as: 'view_interview'

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def new
    @company = current_user
    @positions = @company.positions

    # Delete all previous matched candidates
    MatchedStudent.delete_all(['company_id = ?', @company.id])

    importance = [0.5, 0.3, 0.2]
    @positions.each do |pos|
      possible_students = StudentTest.select("user_id").where(
        'skill_list_id in (?)', [pos.skill_1, pos.skill_2, pos.skill_3]).group(:user_id)

      possible_students.each do |st|
        score_1 = 0
        score_2 = 0
        score_3 = 0

        # Calculate first test score
        unless pos.skill_1.blank?
          test_record = StudentTest.where('user_id = ? and skill_list_id =?', st.user_id, pos.skill_1).first

          if test_record.blank? || test_record.result.blank?
            score_1 = 0
          else
            score_1 = test_record.result * importance[pos.importance_1.to_i - 1]
          end
        end

        # Calculate second test score
        unless pos.skill_2.blank?
          test_record = StudentTest.where('user_id = ? and skill_list_id =?', st.user_id, pos.skill_2).first

          if test_record.blank? || test_record.result.blank?
            score_2 = 0
          else
            score_2 = test_record.result * importance[pos.importance_2.to_i - 1]
          end
        end

        # Calculate third test score
        unless pos.skill_3.blank?
          test_record = StudentTest.where('user_id = ? and skill_list_id =?', st.user_id, pos.skill_3).first

          if test_record.blank? || test_record.result.blank?
            score_3 = 0
          else
            score_3 = test_record.result * importance[pos.importance_3.to_i - 1]
          end
        end

        total_score = score_1 + score_2 + score_3
        if total_score > 0
          interview = MatchedStudent.interview_info(@company.id, st.user_id, pos.id)
          if interview.nil?
            MatchedStudent.create(
              company_id: @company.id, 
              student_id: st.user_id, 
              position_id: pos.id, 
              matching_score: total_score
            )
          else
            MatchedStudent.create(
              company_id: @company.id, 
              student_id: st.user_id, 
              position_id: pos.id, 
              matching_score: total_score,
              interview_sent: interview.status
            )
          end
        end
      end
    end

    @matched_candidates = MatchedStudent.where('company_id = ?', @company.id)
  end

  def get_student
    candidate = User.includes(:experiences).includes(:skills).find(params.permit(:id)[:id])

    if candidate.nil?
      render :json => {errors: "Could not retrieve candidate profile."}, status: :unprocessible_entity and return
    else
      candidate_json = {
        :student_id     => candidate.id,
        :name           => candidate.name,
        :email          => candidate.email,
        :country         => candidate.country_id.nil? ? '' : Country.find(candidate.country_id).name,
        :province       => candidate.province_id.nil? ? '' : Province.find(candidate.province_id).name,
        :phone_number   => candidate.phone_number,
        :academic_status => candidate.academic_status,
        :study_field    => candidate.study_field_id.nil? ? '' : StudyField.find(candidate.study_field_id).name,
        :school         => candidate.school,
        :major          => candidate.major,
        :birth_year     => candidate.birth_year,
        :photo          => candidate.photo.url
      }.to_json

      render :json => {
        :success => true, 
        :candidate => candidate_json, 
        :experience => candidate.experiences.to_json,
        :skill => candidate.skills.to_json
      }, status: :created and return
    end
  end

  def request_interview
    old_interview = Interview.where(
      'company_id = ? and student_id = ? and position_id = ?', 
      current_user.id, 
      params[:interview][:student_id],
      params[:interview][:position_id]
    ).first

    matched_student = MatchedStudent.where(
      'company_id = ? and student_id = ? and position_id = ?', 
      current_user.id, 
      params[:interview][:student_id],
      params[:interview][:position_id]
    ).first
    
    if old_interview.nil?
      interview = Interview.new permit_request_interview_param
      interview.company_id = current_user.id
      interview.sent_date = Time.now
      interview.status = Interview::SENT
      interview.matching_score = matched_student.matching_score
      interview.save

    else
      old_interview.update_attributes permit_request_interview_param
    end

    redirect_to company_candidate_path
  end

  private

  def permit_request_interview_param
    params.require(:interview).permit :position_id, :student_id, :interview_datetime, :description
  end

end

app/views/candidates/_interview_request.slim
.modal.fade.in#interview_request
  .modal-dialog
    .modal-content
      .modal-header.text-center
        button.close data-dismiss="modal" x
        h3.semibold.modal-title.text-success Interview Request
      = form_for :interview, url: request_interview_path, method: :post do |f|
        .modal-body
          .row
            .col-md-12
              .form-group
                = f.label :interview_datetime, "Interview Date/Time", class: "control-label"
                = f.text_field :interview_datetime, class: "form-control", placeholder: "Select date and time"
              .form-group
                = f.label :description, "Description", class: "control-label"
                = f.text_area :description, class: "form-control", placeholder: "", rows: "5"
        .modal-footer
          .row
            .col-md-4.col-md-offset-4
                = f.submit 'Request for Interview', class: "btn btn-success btn-block"
                = f.hidden_field :student_id, id: "student_id"
                = f.hidden_field :position_id, id: "position_id"

app/views/candidates/_matched_student.slim
.modal.fade.in#matched_student
  .modal-dialog
    .modal-content
      .modal-header.text-center
        button.close data-dismiss="modal" x
        h3.semibold.modal-title.text-success Student Profile
      .modal-body.bgcolor-white
        .row
          .col-md-6.text-center
            img#profile_photo width="100%"
          .col-md-6
            br
            br
            address
              strong Name: 
              span#profile_name Dennis Chan
            address
              strong Email: 
              span#profile_email dennischan8782@gmail.com
            address
              strong Phone Number: 
              span#profile_phonenumber 111-111-1111
            address
              strong Birth Year: 
              span#profile_birthyear 1990
            address
              strong Country: 
              span#profile_country China
            address
              strong Province: 
              span#profile_province Beijing
        br
        .row
          .col-md-6
            address
              strong School: 
              span#profile_school High School
          .col-md-6
            address
              strong Academic Status: 
              span#profile_academic High School
        .row
          .col-md-6
            address
              strong Major: 
              span#profile_major Major
          .col-md-6
            address
              strong Study Field: 
              span#profile_study Study Field

        .row
          .col-md-12
            h4 Experiences
            table#table1.table.table-bordered.table-hover
              thead
                tr
                  th.col-md-6 Experience
                  th.col-md-6 Date
              tbody#experience_body

        .row
          .col-md-12
            h4 Skills
            .row#skill_body
            
      .modal-footer

app/views/candidates/new.slim
== render '/layouts/company_top'
/! START Template Main
section#main role="main" 
  /! START Template Container
  .container

    /! START row
    .row
      == render '/layouts/company_left'
       
      /! / Left / Top Side
      /! Left / Bottom Side
      .col-sm-9
        = render 'shared/messages'
        /! START Tab-content
        .tab-content
          .row
            .col-md-12
              - unless @positions.empty?
                - @positions.each_with_index do |pos, pos_idx|
                  .panel.panel-default.form-horizontal.form-bordered
                    /! panel heading/header
                    .panel-heading.pt0.pb0
                      h4.semibold.text-primary 
                        small.text-primary
                          i.ico-list
                        | &nbsp;#{pos.name}

                    .panel-body
                      - if pos.matched_students.empty?
                        h6.semibold.text-center There is no matched candidate in this position.      
                      - else
                        - pos.matched_students.each_with_index do |st, st_idx|
                          .col-sm-3
                            /! team #1
                            .overflow-hidden.text-center
                              /! avatar
                              a href="#" remote="true" data-toggle="modal" data-id="#{st.student.id}" onclick="showProfile(#{pos.id}, #{st.student.id})"
                                = image_tag st.student.photo.url(:medium), class: "img-rounded", width: "100%", class: "img-thumbnail"
                              /! / avatar
                              /! panel body
                              div
                                h5.semibold.ellipsis.text-center = st.student.name
                                p.nm.text-accent Matching Score: #{st.matching_score}%
                                p.nm Interview Status: #{st.interview_sent}
                                hr.mtb5
                                a href="#" onclick="showRequestInterview(#{pos.id}, #{st.student.id})" Request Interview

              - else
                h6.semibold.text-center There is no position in your company!
== render '/candidates/interview_request'
== render '/candidates/matched_student'