config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'
  
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

  get '/provinces', to: 'provinces#get_by_country', as: 'provinces'

  get '/company', to: 'companies#dashboard', as: 'company_dashboard'

  get '/student', to: 'students#dashboard', as: 'student_dashboard'
  post '/student/update_profile', to: 'students#update_profile', as: 'update_student_profile'
  post '/student/experience', to: 'students#create_experience', as:'create_student_experience'
  delete '/student/:id/experience', to: 'students#destroy_experience', as: 'destroy_student_experience'
  get '/student/company', to: 'students#company_profile', as: 'student_company_profile'
  post '/student/skill', to: 'students#create_skill', as:'create_student_skill'
  post '/student/verify', to: 'students#verify_skills', as: 'verify_student_skills'
  delete '/student/:id/skill', to: 'students#destroy_skill', as: 'destroy_student_skill'
  get '/student/interview/:id/accept', to: 'students#accept_interview', as: 'accept_interview'
  get '/student/interview/:id/deny', to: 'students#deny_interview', as: 'deny_interview'
  delete '/student/:id/interview', to: 'students#destroy_interview', as: 'destroy_student_interview'

  get '/company/profile', to: 'companies#profile', as: 'company_profile'
  post '/company/profile', to: 'companies#update_profile', as: 'company_profile_update'
  post '/company/position', to: 'companies#position', as: 'company_position'
  delete '/company/:id/position', to: 'companies#destroy_position', as: 'company_position_destroy'
  get '/company/candidate', to: 'candidates#new', as: 'company_candidate'
  get '/company/candidate/student', to: 'candidates#get_student', as: 'candidate_profile'
  post '/company/candidate/request-interview', to: 'candidates#request_interview', as: 'request_interview'

  get '/company/interview', to: 'interviews#interview_sent', as: 'interview_sent'
  get '/company/interview-scheduled', to: 'interviews#interview_scheduled', as: 'interview_scheduled'
  get '/company/interview-denied', to: 'interviews#interview_denied', as: 'interview_denied'
  delete '/company/:id/interview', to: 'interviews#destroy', as: 'destroy_interview'
  get '/company/:id/interview', to: 'interviews#view', as: 'view_interview'

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_basedata

  def dashboard
    @company = current_user

    @positions = @company.positions
    @position = Position.new
  end

  def profile
    @company = current_user
  end

  def update_profile

    @company = current_user
    if @company.update_attributes permit_params
      redirect_to company_profile_update_path, :notice => "Profile is successfully updated."
    else
      redirect_to company_profile_update_path, :alert => "Failed to update profile."
    end

  end

  def position
    @position = current_user.positions.build permit_position_params

    if @position.save
      redirect_to company_dashboard_path, :notice => "Position is successfully saved."
    else
      redirect_to company_dashboard_path, :alert => "Failed to save experience."
    end

  end

  def destroy_position
    pos = current_user.positions.find params[:id]

    if pos.destroy
      redirect_to company_dashboard_path, notice: "Position was successfully deleted."
    else
      redirect_to company_dashboard_path, alert: "Failed to delete position."
    end
  end

  private

  # Pass parameters to controller
  def permit_params
    if params[:user][:password].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end

    if params[:user][:photo].blank?
      params[:user].delete :photo
    end

    params.require(:user).permit :email, :password, :name, :company_name, :phone_number, :position, 
                                  :website, :description, :photo
                                 
  end

  def permit_experience_params
    params.require(:experience).permit :experience, :date_from, :date_to
  end

  def permit_skill_params
    params.require(:skill).permit :skill
  end

  def permit_position_params
    if params[:position][:skill_1].blank?
      params[:position].delete :skill_1
      params[:position].delete :importance_1
    end

    if params[:position][:skill_2].blank?
      params[:position].delete :skill_2
      params[:position].delete :importance_2
    end

    if params[:position][:skill_3].blank?
      params[:position].delete :skill_3
      params[:position].delete :importance_3
    end
    
    params.require(:position).permit :name, :skill_1, :importance_1, :skill_2, :importance_2, :skill_3, :importance_3
  end
end

app/views/companies/dashboard.slim
== render '/layouts/company_top'
/! START Template Main
section#main role="main" 
  /! START Template Container
  .container

    /! START row
    .row
      == render '/layouts/company_left'
       
      /! / Left / Top Side
      /! Left / Bottom Side
      .col-sm-9
        = render 'shared/messages'
        /! START Tab-content
        .tab-content
          .row
            .col-md-12
              /! START panel
              .panel.panel-default.form-horizontal.form-bordered
                /! panel heading/header
                .panel-heading.pt0.pb0
                  h4.semibold.text-primary
                    small.text-primary
                      i.ico-list
                    | &nbsp;Hiring Questionuire
                /! / panel heading/header
                /! panel body
                .panel-body
                  - @positions.each do |p|
                    .col-md-6.mb10
                      .panel.panel-info
                        /! panel heading/header
                        .panel-heading.no-padding
                          h3.panel-title.text-center
                            = p.name
                        /! panel body with collapse capable
                        .panel-collapse.pull.out
                          .panel-body.pb5
                            .row
                              - unless p.skill_1.blank?
                                .col-sm-6.col-xs-6.text-right
                                  b = p.skill_1_name
                                .col-sm-6.col-xs-6 Importance #{p.importance_1} 
                            .row
                              - unless p.skill_2.blank?
                                .col-sm-6.col-xs-6.text-right
                                  b = p.skill_2_name
                                .col-sm-6.col-xs-6 Importance #{p.importance_2} 
                            .row
                              - unless p.skill_3.blank?
                                .col-sm-6.col-xs-6.text-right
                                  b = p.skill_3_name
                                .col-sm-6.col-xs-6 Importance #{p.importance_3}
                            .row
                              .text-right
                                = link_to company_position_destroy_path(p), class: 'btn btn-xs', method: :delete, 'data-confirm' => 'Are you sure?' do
                                  span.ico-remove3

                  /! Add new Position Information
                  .col-md-12
                    = form_for @position, url: company_position_path, method: :post, html: { class: 'panel panel-default form-horizontal form-bordered' } do |f|
                      .panel-body
                        .form-group
                          .col-md-8.col-md-offset-2
                            = f.label :name, 'Position', class: 'control-label col-sm-4'
                            .col-sm-8
                              = f.text_field :name, class: 'form-control', placeholder: 'Position Title'
                        .form-group
                          .col-md-6
                            = f.label :skill_1, 'Required skill 1', class: 'control-label'
                            = f.select :skill_1, @skill_lists.collect {|c| [c.name, c.id]}, {prompt: 'Select skill'}, class: 'form-control'
                          .col-md-6
                            = f.label :importance_1, 'Importance', class: 'control-label'
                            = f.select :importance_1, [["Importance 1", 1], ["Importance 2", 2], ["Importance 3", 3]], {prompt: 'Select importance'}, class: 'form-control'
                        .form-group
                          .col-md-6
                            = f.label :skill_2, 'Required skill 2', class: 'control-label'
                            = f.select :skill_2, @skill_lists.collect {|c| [c.name, c.id]}, {prompt: 'Select skill'}, class: 'form-control'
                          .col-md-6
                            = f.label :importance_2, 'Importance', class: 'control-label'
                            = f.select :importance_2, [["Importance 1", 1], ["Importance 2", 2], ["Importance 3", 3]], {prompt: 'Select importance'}, class: 'form-control'
                        .form-group
                          .col-md-6
                            = f.label :skill_3, 'Required skill 3', class: 'control-label'
                            = f.select :skill_3, @skill_lists.collect {|c| [c.name, c.id]}, {prompt: 'Select skill'}, class: 'form-control'
                          .col-md-6
                            = f.label :importance_3, 'Importance', class: 'control-label'
                            = f.select :importance_3, [["Importance 1", 1], ["Importance 2", 2], ["Importance 3", 3]], {prompt: 'Select importance'}, class: 'form-control'
                        .col-md-6.col-md-offset-3.text-center
                            = f.submit 'Add Position', class: 'btn btn-success'

app/views/companies/profile.slim
== render '/layouts/company_top'
/! START Template Main
section#main role="main" 
  /! START Template Container
  .container

    /! START row
    .row
      == render '/layouts/company_left'
       
      /! / Left / Top Side
      /! Left / Bottom Side
      .col-sm-9
        = render 'shared/messages'
        /! START Tab-content
        .tab-content
          .row
            .col-md-12
              /! START panel
              = form_for @company, url: company_profile_update_path, method: :post, html: { multipart: true, class: 'panel panel-default form-horizontal form-bordered' } do |f|
                /! panel heading/header
                .panel-heading.pt0.pb0
                  h4.semibold.text-primary
                    small.text-primary
                      i.ico-list
                    | &nbsp;Company Profile
                /! / panel heading/header
                /! panel body
                .panel-body
                  .form-group
                    = f.label :name, 'Your Full Name', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :name, class: 'form-control', placeholder: 'Your name'
                  .form-group
                    = f.label :email, 'Enter your email', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :email, class: 'form-control', placeholder: 'Email address'
                  .form-group
                    = f.label :password, class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :password, class: 'form-control', type: 'password'
                  .form-group
                    = f.label :password_confirmation, class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :password_confirmation, class: 'form-control', type: 'password'
                  .form-group
                    = f.label :company_name, 'Your Company Name', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :company_name, class: 'form-control', placeholder: 'Company name'
                  .form-group
                    = f.label :website, 'Comapny Website URL', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :website, class: 'form-control', placeholder: 'http://'
                  .form-group
                    = f.label :position, 'Your position', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :position, class: 'form-control', placeholder: 'Your position in company'
                  .form-group
                    = f.label :phone_number, 'Your Phone Number', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_field :phone_number, class: 'form-control', placeholder: '+1-555-555-5555'
                  .form-group
                    = f.label :description, 'About Your Company', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.text_area :description, class: 'form-control', rows: '5'
                  .form-group
                    = f.label :photo, 'About Your Company', class: 'col-sm-3 control-label'
                    .col-sm-9
                      = f.file_field :photo, class: 'form-control'
                .panel-footer.text-right
                  = f.button 'Save Changes', class: 'btn btn-success'
                  
                /! / panel body
              /! END panel