config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'
  
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

  get '/provinces', to: 'provinces#get_by_country', as: 'provinces'

  get '/company', to: 'companies#dashboard', as: 'company_dashboard'

  get '/student', to: 'students#dashboard', as: 'student_dashboard'
  post '/student/update_profile', to: 'students#update_profile', as: 'update_student_profile'
  post '/student/experience', to: 'students#create_experience', as:'create_student_experience'
  delete '/student/:id/experience', to: 'students#destroy_experience', as: 'destroy_student_experience'
  get '/student/company', to: 'students#company_profile', as: 'student_company_profile'
  post '/student/skill', to: 'students#create_skill', as:'create_student_skill'
  post '/student/verify', to: 'students#verify_skills', as: 'verify_student_skills'
  delete '/student/:id/skill', to: 'students#destroy_skill', as: 'destroy_student_skill'
  get '/student/interview/:id/accept', to: 'students#accept_interview', as: 'accept_interview'
  get '/student/interview/:id/deny', to: 'students#deny_interview', as: 'deny_interview'
  delete '/student/:id/interview', to: 'students#destroy_interview', as: 'destroy_student_interview'

  get '/company/profile', to: 'companies#profile', as: 'company_profile'
  post '/company/profile', to: 'companies#update_profile', as: 'company_profile_update'
  post '/company/position', to: 'companies#position', as: 'company_position'
  delete '/company/:id/position', to: 'companies#destroy_position', as: 'company_position_destroy'
  get '/company/candidate', to: 'candidates#new', as: 'company_candidate'
  get '/company/candidate/student', to: 'candidates#get_student', as: 'candidate_profile'
  post '/company/candidate/request-interview', to: 'candidates#request_interview', as: 'request_interview'

  get '/company/interview', to: 'interviews#interview_sent', as: 'interview_sent'
  get '/company/interview-scheduled', to: 'interviews#interview_scheduled', as: 'interview_scheduled'
  get '/company/interview-denied', to: 'interviews#interview_denied', as: 'interview_denied'
  delete '/company/:id/interview', to: 'interviews#destroy', as: 'destroy_interview'
  get '/company/:id/interview', to: 'interviews#view', as: 'view_interview'

end

app/views/layouts/_company_left.slim
/! Left / Top Side
.col-sm-3
  /! figure with progress
  ul.list-table
    li.text-center
      = image_tag current_user.photo.url, class: '', width: "100%"

  br
  .section-header.section-header-bordered.mb10
    h5.section-title
      p.font-alt.nm Our Company
  address
    = link_to current_user.website, current_user.website

  /! tab menu
  ul.list-group.list-group-tabs
    li.list-group-item
      = link_to company_candidate_path do
        i.ico-user2.mr5
        | Matched Candidates
    li.list-group-item
      = link_to company_dashboard_path do
        i.ico-question-sign.mr5
        | Hiring Questionuire
    li.list-group-item
      = link_to company_profile_path do
        i.ico-profile.mr5
        | Edit Profile
    li.list-group-item
      = link_to interview_sent_path do
        i.ico-calendar.mr5
        | Interview Requests Sent
    li.list-group-item
      = link_to interview_scheduled_path do
        i.ico-calendar5.mr5
        | Scheduled Interviews
    li.list-group-item
      = link_to interview_denied_path do
        i.ico-calendar-empty.mr5
        | Interview Request Denied
  /! tab menu

app/views/layouts/_company_top.slim
/! START Template Header
header#header.navbar.navbar-fixed-top
  /! START navbar header
  .navbar-header
    /! Brand
    a.navbar-brand href="javascript:void(0);" 
      span.logo-figure.dream-logo-figure
    /! / Brand
  /! START Toolbar
  .navbar-toolbar.clearfix
    /! START Right nav
    ul.nav.navbar-nav.navbar-right
      /! Profile dropdown
      li.dropdown.profile
        = link_to destroy_user_session_path, class: "dropdown-toggle", method: :delete
          span.meta
            span.avatar
              = image_tag current_user.photo.url(:thumb), class: 'img-circle'
            span.text.hidden-xs.hidden-sm.pl5 Sign Out
/! / END Template Header

app/views/layouts/_frontend_footer.slim
.footer-bottom
  .container
    .row
      .col-sm-6.col-sm-offset-3
        p.nm.text-muted
          | &copy; 2014 - 2015 All Rights Reserved for 
          a.text-white href="javascript:void(0);"  Flydge &nbsp;

app/views/layouts/_frontend_header.slim
.navbar-header
  a.navbar-brand href="javascript:void(0);" 
    span.logo-figure.dream-logo-figure style="margin-left:-4px;" 
.navbar-toolbar.clearfix
  #dropdown-form.navbar-form.navbar-left.dropdown
    form action="" role="search" 
      .has-icon
        input.form-control placeholder=("Search this site...") type="text" 
          i.ico-search.form-control-icon
  #navbar-collapse.collapse.navbar-collapse.navbar-collapse-alt
    ul.nav.navbar-nav.navbar-right
      li.dropdown
        = link_to '#automate-process', class: 'dropdown-toggle' do
          span.meta
            span.text.text-primary How It Works
      li.dropdown
        = link_to 'mailto:nawei@flydge.com', class: 'dropdown-toggle' do
          span.meta
            span.text.text-primary Contact
      /!li.dropdown
      /! = link_to '', class: 'dropdown-toggle', data: {toggle: 'modal', target: '#signup_main'} do
        /! span.meta
          /!span.text.text-primary Sign Up
      /!li.dropdown
       /!= link_to '', class: 'dropdown-toggle', data: { toggle: "modal", target: '#signin_form' } do
        /!span.meta
        /!span.text.text-primary Log In
/!- content_for :modals
  /!= render 'devise/sessions/signin'
  /!= render 'devise/registrations/company'
  /!= render 'devise/registrations/student'
  /!= render 'devise/registrations/signup_main'

app/views/layouts/_matched_company.slim
.modal.fade.in#matched_company
  .modal-dialog
    .modal-content
      .modal-header.text-center
        button.close data-dismiss="modal" x
        h3.semibold.modal-title.text-success Company Profile
      .modal-body.bgcolor-white
        .row
          .col-md-6.text-center
            img#profile_photo width="100%"
          .col-md-6
            address
              strong Name: 
              span#profile_name Dennis Chan
            address
              strong Company Name: 
              span#profile_companyname Google
            address
              strong Email: 
              span#profile_email dennischan8782@gmail.com
            address
              strong Phone Number: 
              span#profile_phonenumber 111-111-1111
            address
              strong Company Website: 
              span#profile_website www
            address
              strong Country: 
              span#profile_country China
            address
              strong Position: 
              span#profile_position CTO
      .modal-footer

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title Flydge
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'De Rails'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      /!== render 'layouts/navigation'
    main[role="main"]
      == yield

app/views/layouts/frontend.html.slim
doctype html
html.frontend
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'De Rails'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'De Rails'}"
    == stylesheet_link_tag "frontend", :media => 'all', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header#header.navbar.navbar-fixed-top
      .container
        == render '/layouts/frontend_header'

    section#main role="main"
      == yield

    footer#footer role="contentinfo"
      == render '/layouts/frontend_footer'

    == yield :modals

    == javascript_include_tag 'frontend', 'data-turbolinks-track' => true